version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./conf.d:/etc/mysql/conf.d"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --innodb-use-native-aio=0
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql